apiVersion: v1
kind: ConfigMap
metadata:
  name: speed-showdown-config
  labels:
    app: speed-showdown
data:
  vllm-url: "https://maas.apps.ocp.cloud.rhai-tmm.dev/v1"
  standard-llm-url: "https://maas.apps.ocp.cloud.rhai-tmm.dev/v1"
  model-name: "Qwen/Qwen3.5-9B"
