apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: speed-showdown

resources:
  - deployment.yaml
  - buildconfig.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: speed-showdown
  app.kubernetes.io/part-of: four-pillars-ai
  app.kubernetes.io/pillar: inference-vllm
