apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scoreboard-storage
  namespace: speed-showdown
  labels:
    app: speed-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibmc-vpc-block-10iops-tier
